# -*- coding: utf-8 -*-
"""Question_1_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zOhmgIQbWV3walBDMsRaxbuYOn4HI2T9
"""

import numpy as np
import matplotlib.pyplot as plt

c = 3e8
E0 = np.array([30, 30, 30])
B0 = np.array([1e-7, 1e-7, 1e-7])
beta = np.linspace(0, 0.9999, 1000)
E_gt = np.linalg.norm(E0) * np.ones(1000)
E_lt = []

for i in beta:
    v = i * c
    gam = 1 / np.sqrt(1 - i**2)
    Ex = E0[0]
    Ey = gam * (E0[1] - v * B0[2])
    Ez = gam * (E0[2] + v * B0[1])
    E_lt.append(np.linalg.norm([Ex, Ey, Ez]))

plt.plot(beta, E_gt, label="Galilean transform")
plt.plot(beta, E_lt, label="Lorentz transform")
plt.xlabel("v/c")
plt.ylabel("|E|")
plt.legend()
plt.grid()
plt.title('Plot of the transformation of electric fields in GT and LT')
plt.show()