# -*- coding: utf-8 -*-
"""Question_2_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_92SU9-hZ00OqMXZQtuC2r23TRAyOyx
"""

import numpy as np
import matplotlib.pyplot as plt

phi = np.arctan(0.01) #for v/c value = 0.01. we have to change this value for getting the plots for all the three cases

x_ax  = np.array([1, 0])
ct_ax = np.array([0, 1])

rot = np.array([
    [np.cos(phi), -np.sin(phi)],
    [np.sin(phi),  np.cos(phi)]
])

x_p  = np.dot(rot, x_ax)
ct_p = np.dot(rot, ct_ax)

plt.plot([0, x_p[0]],  [0, x_p[1]], 'r--', label="x'")
plt.plot([0, ct_p[0]], [0, ct_p[1]], 'b--', label="ct'")
plt.axhline(0, color='black')
plt.axvline(0, color='black')
plt.xlabel("x",size=15)
plt.ylabel("ct",size=15)
plt.legend()
plt.title(f"Lorentz boost with φ = {phi}")
plt.show()